// <auto-generated />
using System;
using BOSSAProje.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BOSSAProje.Migrations
{
    [DbContext(typeof(CihazContext))]
    partial class CihazContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BOSSAProje.Models.Cihaz", b =>
                {
                    b.Property<string>("SERI_NO")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BULUNDUGU_YER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CALISIYOR_MU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("CIHAZ_ALT_GRUBU")
                        .HasColumnType("real");

                    b.Property<string>("CIHAZ_ALT_GRUP_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("CIHAZ_GRUBU")
                        .HasColumnType("real");

                    b.Property<string>("CIHAZ_GRUBU_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIHAZ_MODELI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIHAZ_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPARTMAN_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPARTMAN_KODU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FABRIKA_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("FABRIKA_KOD")
                        .HasColumnType("real");

                    b.Property<string>("ISY_KODU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KULLANICI_AD_SOYAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KULLANICI_SICIL_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MODEL_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Markası")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERT_MI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROCESSOR_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROCESSOR_KODU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIRKET_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIRKET_KODU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sayi")
                        .HasColumnType("int");

                    b.HasKey("SERI_NO");

                    b.ToTable("Cihaz", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
